import NextHead from 'next/head'

const defaultTitle = 'Is it gpt-3?'

export default function Head({
  title,
  description,
}: {
  title?: string
  description?: string
}) {
  const metaTitle = title ? `${title} | ${defaultTitle}` : defaultTitle
  const metaDescription =
    description ||
    `${defaultTitle} is a web app to check if the text is generated by GPT-3 or not.`

  return (
    <NextHead>
      <title>{metaTitle}</title>

      <link rel='icon' type='image/png' href='/isgpt3-favicon.png' />

      <meta name='description' content={metaDescription} />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
    </NextHead>
  )
}
